### ISSUE TITLE
Deferred is not defined

### ISSUE THREAD

**Issue by forensicsguy20012004** [gaelazzo/edge-sql#1]
When using some of the functions described ... I receive the following error: Deferred is not defined

**Comment by gaelazzo** [comment]
You need to intall and use   [JQDeferred](https://www.npmjs.com/package/JQDeferred) to your project

**Comment by forensicsguy20012004** [comment]
Thank you for the clarification.

**Comment by forensicsguy20012004** [comment]
Excellent... Good work.I would love to work with you on other projects.
