### ISSUE TITLE
Request for documentation

### ISSUE THREAD

**Issue by forensicsguy20012004** [gaelazzo/edge-sql#2]
Could some "real world" documentation be produced and included in the git repository? Really, I would like to see how to use a "real-world" select statement that returns json data that is not in the "meta" and "rows" format but in a "field": "value" format. Thank you in advance.

**Comment by gaelazzo** [comment]
You can see an example of use in my https://github.com/gaelazzo/jsSqlServerDriver. 
To get a {field:value,..}  
you take the meta and the rows and pass them to simpleObjectify.
so you call simpleObjectify(meta, rows) and it gives you {field:value..}
It's that simple.

For example if you read queryBatch function, it ends with

```
 if (raw) {
            def.resolve(result[i]);
        } else {
            def.resolve(simpleObjectify(result[i].meta, result[i].rows));
        }
```

**Comment by forensicsguy20012004** [comment]
Hello again....I was able to get this working...I had to modify in the
loop, originally the code was [result.length-1] but noticed that i would
always equal 0 and I found that if I did a result.length it would equal
1...so i would never be greater than 0 and it would never hit the
looping....once I played around with the "for" section...I was able to get
it work and now my queries are returning exactly as expected.

So with that said, what was I missing? Did I mess things up in my code base
by removing the -1 aspect. I am interested to know.

Matt

```
 var resultset
        var i;
```

   for (i=0; i< result.length; i++)
   {
       resultset = (simpleObjectify(result[i].meta, result[i].rows))
   }

**Comment by gaelazzo** [comment]
It was only an example of use. I took it from [jsSqlServerDriver](https://github.com/gaelazzo/jsSqlServerDriver/blob/master/src/jsSqlServerDriver.js)

```
Connection.prototype.queryBatch = function (query, raw) {
    var edgeQuery = edge.func(this.sqlCompiler, _.assign({source: query}, this.getDbConn())),
        def = Deferred();
    edgeQuery({}, function (error, result) {
        if (error) {
            def.reject(error+' running '+query);
            return;
        }
        var i;
        for (i = 0; i < result.length - 1; i++) {
            if (raw) {
                def.notify(result[i]);
            } else {
                def.notify(simpleObjectify(result[i].meta, result[i].rows));
            }
        }
        if (raw) {
            def.resolve(result[i]);
        } else {
            def.resolve(simpleObjectify(result[i].meta, result[i].rows));
        }
    });
    return def.promise();
};
```

it was written separating notifications (notify()) of first N-1 packets (that could be different result set of a same query batch for example) from the last that is given with the last resolve().
It was done to give some data with the resolve().
So you can query something like "select \* from A; select \* from B;.." in a single batch.
