### ISSUE TITLE
Support for Node 6.x.x

### ISSUE THREAD

**Issue by forensicsguy20012004** [gaelazzo/edge-sql#3]
Long time since we last chatted....I hope all is well. I was wondering when the main project edge-sql gets updated to run on the latest Node version will  you need to re-compile anything or will we be good to role? Let me know I am interested. Also did you see there is a Slack Channel called 'edgejs?' Anyway, this is not a bug or defect just asking a question.....Thanks Matt

**Comment by gaelazzo** [comment]
I'm using it with any version without having any problem. If you have, let me know.
I sincerely don't know what a "slack channel" is.

**Comment by forensicsguy20012004** [comment]
Ok, cool...you can close this out...

Thank you again. You do GREAT WORK.

So from https://github.com/tjanczuk/edge 

NEW Edge.js is now on Slack at https://edgejs.slack.com. Join here.

![image](https://cloud.githubusercontent.com/assets/12624999/15505436/937d4ba4-2191-11e6-8e2a-37213bdecd9e.png)
