### ISSUE TITLE
Question...more of what is the best approach 

### ISSUE THREAD

**Issue by forensicsguy20012004** [gaelazzo/edge-sql#4]
Good Sir,
So I was thinking of adding additional functionality to my Node/SQL project by allowing users to take dB backups. The TSQL is not the issue but if wanted to stream the results back to the calling API for example, say at every 10 percent , respond but not completely close the connection to the client until 100 percent....what would be tour recommended approach? Thanks....Matt

**Comment by gaelazzo** [comment]
It could be done on a table-by-table bases, counting rows on each table and returning a set of rows every N/10 rows where N is the count(*) of the table...

**Comment by forensicsguy20012004** [comment]
Yeah I agree, but how would that work for a database backup script that emits stats at every 10 percent? Is this more of a Socket.IO thing so that when a value is emitted from the backup that data is fired to a socket channel?

**Comment by gaelazzo** [comment]
Sorry I have never  used those kind of stats you are talking of, so I can't help you
